data1 <- read.table("F:/coursera/household_power_consumption.txt",header =TRUE,sep =";",na.string ="?")
data2 <- subset(data1, Date =="1/2/2007" | Date =="2/2/2007")
data2$DateTime <-paste(data2$Date, data2$Time)
data2$DateTime <- strptime(data2$DateTime, "%d/%m/%Y %H:%M:%S")
plot(data2$DateTime,data2$Sub_metering_1,type ="l",xlab ="", ylab ="Energy sub metering")
lines(data2$DateTime,data2$Sub_metering_2,type ="l",ylab ="Energy sub metering",col ="red")
lines(data2$DateTime,data2$Sub_metering_3,type ="l",ylab ="Energy sub metering",col ="blue")
legend("topright",pch ="——",col =c("black","red","blue"),legend =c("sub_metering_1               ","sub_metering_2               ","sub_metering_3                "))
dev.copy(png,file ="plot3.png",height=480, width=480)
dev.off()